apiVersion: v1
kind: ConfigMap
metadata:
  name: java-ms
  namespace: default
data:
  spring.session.store-type: redis
  spring.redis.host: eks-el-1jnl5h2uytq8v.euyr0d.0001.aps1.cache.amazonaws.com
  spring.redis.port: '6379'